### ISSUE TITLE
Me gustaria modificar una tarjeta para agregar mi perfil

### ISSUE THREAD

**Issue by ReynagaMatias** [Cam-Bane/devtech-podcast-web#1]
Me gustaria modificar una tarjeta para agregar mi avatar: 
quedaria mas o menos asi...
![image](https://user-images.githubusercontent.com/38359386/178826967-76f5c7e3-9601-4c11-82b8-60e2d48dd540.png)

**Comment by Cam-Bane** [comment]
Estoy de acuerdo, saludos.
